### ISSUE TITLE
[BUG] iOS EmailValidator 

### ISSUE THREAD

**Issue by Jack25apr** [Adyen/adyen-ios#1073]
**Describe the bug**
Hi!
I tested with Adyen [5.0.0] your regex from file **EmailValidator** in iOS library with next invalid emails:
**aa@-aa.aa** 
**qaa@aa-.aa**
(Dash after "@" symbol and dash before " invalid cases), but it seems to be valid using that regex.

PS: I know email validation is pain in the arse sometimes.

**Comment by mohammedDehairy** [comment]
@Jack25apr , Thanks for reporting this :-) ! we'll look into!

**Comment by mohammedDehairy** [comment]
@Jack25apr ,

The issue should be fixed in [this PR](https://github.com/Adyen/adyen-ios/pull/1074), can you please confirm its fixed?

**Comment by Jack25apr** [comment]
@mohammedDehairy 
Thanx for the very fast answer, the main issue i think is fixed.

I just used some strange valid and invalid emails from web, and got some more faulty cases:

1)I got "valid = true" scenario from these invalid emails (got them somewhere from web):

あいうえお@example.com // not encoded non english letters 
just”not”right@example.com // strange quotes inside
1234567890123456789012345678901234567890123456789012345678901234+x@example.com // more than 64 symbols i guess

2)And I have false negative "valid = false" scenarios for ip in emails for these cases:
postmaster@[IPv6:2001:0db8:85a3:0000:0000:8a2e:0370:7334]
jsmith@[IPv6:2001:db8::1] // valid example from wikipedia

but all of these i think are very rare cases.

Thank you!

**Comment by mohammedDehairy** [comment]
@Jack25apr ,

 you're right, the regex was allowing non Latin characters, so I changed the PR a bit to match the wikipedia definition more closely, of course its not 100% correct, because it doesn't check the 64 octet length for the local part and also the IPv6 IP address as domain, but at some point the effort and complexity spent will not have enough return on investment :-).

please let me know if the PR is good enough.

Mohamed

**Comment by Jack25apr** [comment]
@mohammedDehairy  
now its perfect, 
Thank you!
