### ISSUE TITLE
iOS Drop-in - doesn't close when click on cross icon

### ISSUE THREAD

**Issue by anton0243** [Adyen/adyen-ios#1104]
Hello!
i am trying to initialize **drop-in ios 5.0** with **react native** (my custom module) according to this guide:
https://docs.adyen.com/online-payments/ios/drop-in

When I click on the "close" icon - it doesn't close and I get an error in **didFail(extension AdyenSessionDelegate)**:
`The operation couldn’t be completed. (Adyen.ComponentError error 0.)`

Should it work on its own or should I handle it manually?
If so, please help me understand what I could be doing wrong.

![photo_2022-12-19_16-41-09](https://user-images.githubusercontent.com/12491780/208453203-85c24c2a-b571-4d76-85d2-58dc312b0c68.jpg)

**Comment by descorp** [comment]
Hey @anton0243 

This is expected behaviour. We treat "canceled by shopper" event as `didFail` with `ComponentError.cancelled`.
We expect merchant app to perform Drop-In presentation and dismissal.

You can also use our [Demo App code](https://github.com/Adyen/adyen-ios/blob/develop/Demo/Common/IntegrationExampleDropIn.swift) for sample.

**Comment by anton0243** [comment]
@descorp Thank you very much for your answer!

**Comment by anthlasserre** [comment]
> Hey @anton0243
> 
> This is expected behaviour. We treat "canceled by shopper" event as `didFail` with `ComponentError.cancelled`. We expect merchant app to perform Drop-In presentation and dismissal.
> 
> You can also use our [Demo App code](https://github.com/Adyen/adyen-ios/blob/develop/Demo/Common/IntegrationExampleDropIn.swift) for sample.

Hey @descorp 👋🏼  I understand the point of the failure event. But I think in terms of UX it would make sense to hide the modal anyway. We can hide the Drop In and trigger the `didFail` callback in the same time. Otherwise, we need to hard-code a condition to match this specific status code `canceledByShopper` and hide the Drop-In through the component parameter provided.

Let me know WDYT. I might be able to create a PR for that at some point.

**Comment by descorp** [comment]
Hey @anthlasserre 

In general, we try not to alter app's navigation stack, because we don't want to make any assumption of merchant app's behaviour.
In some cases (ex. session expiration, push notification, ect) navigation could happen "behind the scene" and then "dismiss" command on DropIn's presenter could be unpredictable.
