### ISSUE TITLE
[NEED ASSIST] Error in Card3DS2Authenticator while adding Adyen package

### ISSUE THREAD

**Issue by Cernius** [Adyen/adyen-ios#1164]
I've tried to add Adyen to my XCode project via CocoaPods and Swift Package Manager, but either of them shows the same errors in "Card3DS2Authenticator" file while building. Have I missed something while installing the package?

**Errors:**
Swift Compiler Error (Xcode): Extra arguments at positions #2, #3 in call
Pods/Adyen/AdyenCard/Utilities/Card3DS2Authenticator.swift:47:30

Swift Compiler Error (Xcode): Cannot convert value of type 'ADYServiceParameters' to expected argument type 'ADYService'
Pods/Adyen/AdyenCard/Utilities/Card3DS2Authenticator.swift:47:37

Swift Compiler Error (Xcode): Cannot assign value of type '_' to type 'ADYTransaction'
Pods/Adyen/AdyenCard/Utilities/Card3DS2Authenticator.swift:51:35

![image](https://user-images.githubusercontent.com/55694545/221363779-e67e5bab-d427-4631-8648-b371184fe22b.png)

**Comment by descorp** [comment]
Hey @Cernius 

~~Our SDK [does not contain `Card3DS2Authenticator`](https://github.com/Adyen/adyen-ios/search?q=Card3DS2Authenticator) file. What version of SDK is this?~~

Are you using `v2.8.6` ?
If this is true, then problem is most likely incorrect version of 3DS dependency. 
Since last release of v2 library was in 2020, it does not support SPM and may not work on modern Xcode/M1 macs.
Also it is [announced to be deprecated](https://docs.adyen.com/online-payments/classic-integrations/checkout-sdks/ios-sdk).

---

Similar problem was resolved [4 days](https://github.com/Adyen/adyen-ios/issues/1161) ago.
What have changed?

**Comment by descorp** [comment]
Hey @Cernius 

How is it going?
Any update on this?

**Comment by descorp** [comment]
I am going to close this ticket due to lack of activity.
Please feel free to continue here.
