### ISSUE TITLE
[NEED ASSIST] iOS component doesn't provide with an `UIView`

### ISSUE THREAD

**Issue by chuck-gnaw** [Adyen/adyen-ios#1194]
**Describe the challenge**
hey, iOS components doesn't provide with an `UIView` to be used as part of the view on a VC, it only provides the view controller? how do I integrate with component Adyen provide as part of the view? add this VC as child vc and add its view?

Thank you so much

**Comment by descorp** [comment]
Hey @chuck-gnaw 

Thanks for reaching out!

> add this VC as child vc and add its view?

This is correct. We find `UIViewControllers` to be more universal, since it could be used on it's own and as part of other UIViewController.

> how do I integrate

Paul Hudson have a [nice example here](https://www.hackingwithswift.com/example-code/uikit/how-to-use-view-controller-containment).

Please let us know if you have any issues with this approach.
Mind potential issues with safe areas, scrolling and keyboard size.

**Comment by chuck-gnaw** [comment]
> Hey @chuck-gnaw
> 
> Thanks for reaching out!
> 
> > add this VC as child vc and add its view?
> 
> This is correct. We find `UIViewControllers` to be more universal, since it could be used on it's own and as part of other UIViewController.
> 
> > how do I integrate
> 
> Paul Hudson have a nice example here.
> 
> Please let us know if you have any issues with this approach. Mind potential issues with safe areas, scrolling and keyboard size.

hi @descorp thanks for you reply, Do you have the link of Paul Hudson's example?

**Comment by descorp** [comment]
Sorry @chuck-gnaw , I have made a typo in markdown. Check the comment above 😅

**Comment by chuck-gnaw** [comment]
> nice example here

@descorp Thank you very much! have a lovely day

**Comment by rokridi** [comment]
Hi @chuck-gnaw .
Did you manage to display the component in a View ? Did you also try it with SwiftUI ? 
Thanks.
