### ISSUE TITLE
[NEED ASSIST] - Drop in component challenge flow only

### ISSUE THREAD

**Issue by b7anka** [Adyen/adyen-ios#1213]
Hi there, our app was developed without 3DS2 security feature in mind and right now we are finishing the implementation of it with the help of the adyen drop in component because we started having problems with credit cards that were being reject due to the lack of the 3DS2 security feature. One thing that we are unsure of is whether the previous added cards that our users have already added to their accounts (the ones that were not authenticated via 3DS2) will work without the 3DS2 authentication. I believe they will eventually fail as they were never authenticated with 3DS2 and what me and my team would like to know is if the drop in component can pop up the challenge flow only without our users having to enter the card details again. If yes can you point out a documentation link with the instructions on how to do it. Thank you

**Comment by nickalangeloo** [comment]
Hi @b7anka, thank you for your question. 

> One thing that we are unsure of is whether the previous added cards that our users have already added to their accounts (the ones that were not authenticated via 3DS2) will work without the 3DS2 authentication.

This is dependent on the issuer and their risk logic. The issuer checks a reference to identify the recurring payment and link it to the initial payment. If this reference is missing, it most likely resolves in an ["Authentication Required" refused response](https://docs.adyen.com/development-resources/refusal-reasons). If the reference is present, but the initial transaction did not have 3Ds authentication, it depends on the issuer what the outcome of the transaction will be. 

> I believe they will eventually fail as they were never authenticated with 3DS2 and what me and my team would like to know is if the drop in component can pop up the challenge flow only without our users having to enter the card details again.

First of all, I would only initiate this flow if the transaction was actually refused due to missing authentication on the sign up transaction and then contact the shopper as the impact can be less than expected. In case there is impact, the shopper has to come back in-session and perform authentication on a transaction. This transaction can be a "0" amount or an actual amount. Subsequently, it can be performed through your checkout page or by providing the shopper a [Pay By Link](https://docs.adyen.com/unified-commerce/pay-by-link) solution.  
It is possible to avoid the shopper for re-entering their card credentials by sending the "shopper in-session" transaction as an `"shopperInteraction": "ContAuth"` and `"recurringProcessingModel": "CardOnFile"` (see [here](https://docs.adyen.com/online-payments/tokenization/create-and-use-tokens#pay-one-off)) payment. This renders the Drop In with the shopper credentials pre-filled from the token (card credentials present) and identifies to Adyen, schemes and issuers that the shopper is in-session so authentication will be initiated. As a result, the token and the shopper credentials contain the correct requirements and recurring payments can be continued as expected. 

If you have additional questions, I recommend to send an email to support@adyen.com as they assist you more tailored to your situation.

**Comment by b7anka** [comment]
Hi @nickalangeloo, thanks for you reply we will follow your solution only performing the flow if the card is actually refused due to missing authentication.
