### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by waqar1992** [Adyen/adyen-ios#1343]
**Describe the bug**
Hi There,
We are using Adyen Component in our iOS app for payments. We are using SPM 5.1.0 and backend v67. All the components are working fine if we install the build directly from Xcode to simulator and iPhone. However if we export the IPA it present the component but after that it calls 

func didFail(with error: Error, from component: PaymentComponent) {}

**To Reproduce**
1. Exported the IPA 
2. Click on Component
3. Enter card details

**Expected behavior**
After capturing card details it should call
 func didSubmit(_ data: PaymentComponentData, from component: PaymentComponent) {}

**Screenshots**
![image](https://github.com/Adyen/adyen-ios/assets/37799829/0483f6a9-2299-434b-964a-5048146cb851)
![IMG_7702](https://github.com/Adyen/adyen-ios/assets/37799829/eac4c876-6292-4481-875a-7d95d1998c56)

**Environment**
 - Device: [iPhone14pro & iPhone11]
 - iOS Version: [iOS16.6]
 - SDK Version: [5.1.0 & 5.3.0]
 - Adyen API Version: [ 67]
 - Package management system: [ SPM]
 - Xcode version: [e.g 14.3.1]
 - Mac OS type: [e.g. M1 / Intel]

**Comment by malekmalke** [comment]
Hello Waqar, 

As discussed, the issue ended up being related to the authentication with the originating URL being different after exporting the IPA from the originating URL of the Xcode. 

Regards,

**Comment by descorp** [comment]
@waqar1992 @malekmalke 

What was the problem?
Can we close this issue?

**Comment by malekmalke** [comment]
Hi Vlad,

Yes, this can be closed.

The issue was not including the new originating URL after exporting the app
to IPA to the list of allowed origins linked to the client-key being used
which was causing HTTP 500 error.

Regards,
---
Malek Malke
Implementation Manager

mobile: +971526801869
contact: adyen.com/contact <https://www.adyen.com/contact>

Adyen MEA FZ LLC
Arjaan Office Tower
Floor 13, Dubai Media City
Dubai, United Arab Emirates

**Comment by descorp** [comment]
Thanks for clarifying @malekmalke 💚
