### ISSUE TITLE
Security issue - the credit card data are saved in the iPhone memory.

### ISSUE THREAD

**Issue by Fouda** [Adyen/adyen-ios#139]
Currently I am using the Adyen SDK v2.4.0
I got a problem from the security team that my credit card data such as CVV, credit card number, .. are occurring on the memory. 
is the a way using the SDK to encrypt those data or to delete them  the memory ? 
thanks.

**Comment by joostvandijk** [comment]
Hi @Fouda,

The data is encrypted before it's sent to the server. If you require more control over how the data is kept in memory, I would recommend building the UI yourself (using `PaymentController` instead of `CheckoutController` in v2.x), and using the `CardEncryptor` class to encrypt card data.

Best,

Joost

**Comment by Fouda** [comment]
Hello @joostvandijk ,
Thanks a lot for your reply.
