### ISSUE TITLE
How to handle the 3DS cancel button

### ISSUE THREAD

**Issue by SMJ93** [Adyen/adyen-ios#141]
What is the best way to handle the 3DS cancel button on this screen:

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-01-28 at 15 37 13](https://user-images.githubusercontent.com/2145641/73279105-805aba80-41e4-11ea-8555-3884add2e1d7.png)

We can use the following as mentioned in https://github.com/Adyen/adyen-ios/issues/87 for the first cancel:

```
if let error = error as? ComponentError, error == .cancelled {
            // cancelled is true
 }
```

But the 3DS cancel error returns:

```
Error Domain=com.adyen.Adyen3DS2.ADYRuntimeError Code=5 "Challenge has been cancelled." UserInfo={NSLocalizedDescription=Challenge has been cancelled.}
```

So is not handled.

**Comment by mohammedDehairy** [comment]
Hi @SMJ93,

 Thats a good question.

 Actually this error doesn't originate from the Adyen checkout SDK, it originates from Adyen 3DS2 SDK, specifically sent back when a 3DS 2 challenge was canceled by the user.

 so I would say this should work:
```
if (error as NSError).domain == ADYRuntimeErrorDomain, (error as NSError).code == ADYRuntimeErrorCode.challengeCancelled.raw {
     // cancelled is true
}
```

 On our side, maybe we should hide specifically the 3DS 2 cancel error and transform it into a ComponentError.cancelled, instead of reporting back the 3DS 2 specific error.

Hope this helps.

**Comment by SMJ93** [comment]
Hi @mohammedDehairy that works, thanks!

I had to use `.rawValue` and import `import Adyen3DS2`
