### ISSUE TITLE
[BUG] When processing a Payment using an iOS Simulator an error is returned frequently but not always.

### ISSUE THREAD

**Issue by jnorman-control4** [Adyen/adyen-ios#1438]
We're using the iOS SDK and the dropin component.   When processing a payment this error is returned most of the time, but not always:

Adyen.APIError(status: Optional(422), errorCode: "174", errorMessage: "Unable to decrypt data [This error message is only provided on TEST, this error will be a 500 Internal Error on LIVE.]", type: Adyen.APIErrorType.validation

Without changing any code, I'll retry the payment again and it will be 'authorised' eventually.

**To Reproduce**
Integrate the dropin with a test API key
Invoke the dropin with session data
Attempt to process the transaction with a test credit card.  (6011 6011 6011 6611)
 
**Expected behavior**
That the payment is processed without  an error.

**Environment**
 - Device: iOS 15 Pro simulator
 - iOS Version: 17.01
 - SDK Version: 5.2
 - Package management system: SPM
 - Xcode version: 15.0.1
 - Mac OS type: M2

**Comment by goergisn** [comment]
Hi @jnorman-control4,

Thank you for reporting this issue. 
After some investigation it turns out that this bug is related to a change of **JSONEncoder** when building with **Xcode 15**.

This behavior change was addressed in [5.4.0](https://github.com/Adyen/adyen-ios/releases/tag/5.4.0), 
which is the first Checkout SDK version with support for Xcode 15.

Can you confirm if this fixed the issue you're running into?

Best,
Alex

**Comment by jnorman-control4** [comment]
Alex, 
That fixed the issue.  Thanks again for a quick response!
-Jim
