### ISSUE TITLE
Action data couldn’t be read

### ISSUE THREAD

**Issue by laohanme** [Adyen/adyen-ios#150]
Hi, 
I was wondering to figure out this problem, the data couldn't be read, but the data was success return to the client side

![image](https://user-images.githubusercontent.com/18119268/77844998-b664ec80-71dd-11ea-9b51-4cb25ae17186.png)

![image](https://user-images.githubusercontent.com/18119268/77845025-08a60d80-71de-11ea-9c48-856ec417ae58.png)
![image](https://user-images.githubusercontent.com/18119268/77845050-486cf500-71de-11ea-8013-4cbcc6bbb12f.png)

**Comment by mohammedDehairy** [comment]
Hi @laohanme ,

Thanks for reaching out.

 I think the way you parse the JSON is a bit wrong, the "action" dictionary in the JSON response is a child of the "data" dictionary, but your code expects "action" dictionary to be on the same level as "success" boolean.

in order to fix this, the MyPayment needs to implement `init(from decoder: Decoder)` like the following:
```
struct MyPayment: Response {
    
    let success: Bool
    
    let action: Action?
    
    init(from decoder: Decoder) throws {
        let mainContainer = try decoder.container(keyedBy: CodingKeys.self)
        self.success = try mainContainer.decode(Bool.self, forKey: .success)
        let dataContainer = try mainContainer.nestedContainer(keyedBy: DataKeys.self, forKey: .data)
        self.action = try dataContainer.decodeIfPresent(Action.self, forKey: .action)
    }
    
    private enum CodingKeys: String, CodingKey {
        case success
        case data
    }

    private enum DataKeys: String, CodingKey {
        case action
    }
    
}
```

Hope this helps.

Mohamed

**Comment by laohanme** [comment]
Hi @mohammedDehairy,

Thank for responded my issue.

Yes, now i know the problems was on my side
The solution that you provided was helped me a lot. Thank you
