### ISSUE TITLE
[NEED ASSIST] 3D Secure 2 redirect

### ISSUE THREAD

**Issue by Mihailo94** [Adyen/adyen-ios#1502]
**Describe the challenge**
Hi, I'm trying to implement redirect component. I'm getting CVC / CVV error when I enter card details in Adyen component. Also, as you can see card numbers are not grouped together in 4 rows. Any suggestions what it could be?

**Documentation update (optional)**
I found test card [here](https://docs.adyen.com/development-resources/testing/3d-secure-2-authentication/#3d-secure-2-redirect)

**Screenshots**
![IMG_3297](https://github.com/Adyen/adyen-ios/assets/148769359/aa095f93-b94c-41a5-9a88-841b5fa68f99)

**Comment by erenbesel** [comment]
Hello @Mihailo94 

That looks like an American Express card number which needs 4 digits for CVV (the link should be fixed but try 7373). Also, Amex card numbers are formatted 4-6-6 instead of 4-4-4-4.

You can use more test cards on our [test cards](https://docs.adyen.com/development-resources/testing/test-card-numbers) page!

**Comment by Mihailo94** [comment]
@erenbesel Thank you for clarification.

**Comment by Mihailo94** [comment]
Hi @erenbesel, I closed this issue but I stuck on next step for redirect component so I would ask you for help here.

So, RedirectComponent not showing to me. What I did: I created and persist instance of RedirectComponent on the same way as I did for AdyenActionComponent. Here is my code: 

```
internal lazy var redirectComponent: RedirectComponent = {
        let component = RedirectComponent(context: adyenContext)
          component.delegate = self
          component.presentationDelegate = self
          return component
      }()
```
Then decode data and handle action: 

```
action = try JSONDecoder().decode(RedirectAction.self, from: data)
self?.redirectComponent.handle(action)
```
As I understand RedirectComponent should be opened but nothing happened in my case.

Do you know what could be a problem?

**Comment by Mihailo94** [comment]
Hi @erenbesel, could you please help me with this?

**Comment by Mihailo94** [comment]
Hi @erenbesel, any chance to help me with this?

**Comment by erenbesel** [comment]
Hey @Mihailo94 , although it's not possible to figure out from a code piece, my guess would be the action object may not be of type `RedirectAction`. You need to create an `AdyenActionComponent` and call `handle(action...` function on this object instead of the redirect component (you can see these usages in the demo app).

I suggest checking our [docs](https://docs.adyen.com/online-payments/build-your-integration/?platform=iOS&integration=Drop-in&version=5.5.0) and the [demo](https://github.com/Adyen/adyen-ios/tree/develop/Demo) app in this repo for more details.

You can also contact our support team from your Customer Area.

**Comment by Mihailo94** [comment]
Hi @erenbesel, thank you for your response I tried what you suggested before I asked for help but it doesn't work for me.
About your assumption that action object is not type of `RedirectAction` I would say that I use correct object.
```

                var data = Data()
                var action: RedirectAction?

                do {
                    
                    data = try JSONSerialization.data(withJSONObject: actionData.toJSON() as Any, options:[])
                    action = try JSONDecoder().decode(RedirectAction.self, from: data)
                    
                } catch {
                    
                    log.debug("Error during parsing: \(error.localizedDescription)")
                }
                
                guard let action = action else { return }
                
                self?.redirectComponent.handle(action)
```

**Comment by Mihailo94** [comment]
Hi @erenbesel I contacted support team and waiting for response. Also one thing as you mention to try with Demo app. When I use Demo app, enter the data in CardComponent and tap on pay button I get error about shopperInteraction field. Do do know what it could be?
<img width="369" alt="Screenshot 2024-01-19 at 12 50 45" src="https://github.com/Adyen/adyen-ios/assets/148769359/562438dd-ae4b-4f32-9151-7d4e14c1bb14">

**Comment by goergisn** [comment]
Feel free to create a new ticket for anything additional or re-open if your issue is not solved.
