### ISSUE TITLE
Facing issue in credit card payment when keyboard appear

### ISSUE THREAD

**Issue by tejasdthanki** [Adyen/adyen-ios#153]
In iOS SDK version 3.4.1 I am facing below issue.
In credit card payment when keyboard appear ui is messed up.please refer attached screenshot.I am facing issue when there is no any stored payment method in list.
![Screen Shot 2020-04-10 at 11 27 44 AM](https://user-images.githubusercontent.com/63439638/78967044-f8b3f500-7b1e-11ea-9b10-f6aebb822e96.png)

**Comment by descorp** [comment]
Hi @tejasdthanki 

Thanks for reaching out.
This issue was detected yesterday and we are working on a fix.

Sorry for inconvenience.

**Comment by tejasdthanki** [comment]
Hi @descorp 
Thanks for reply.

**Comment by mohammedDehairy** [comment]
Hi @tejasdthanki,

 We released 3.5.0, in which the issue should be fixed, can you verify?.

**Comment by tejasdthanki** [comment]
Hello @descorp / @mohammedDehairy  ,
Thanks.Now this issue is fix in updated version.
I have one question
I wants to change language from my application.can I use "localizationParameters" from PaymentMethodsConfiguration?

If yes then please share example of it.(e.g. initialisation  of localizationParameters for change language)

**Comment by descorp** [comment]
Hi @tejasdthanki 

You can add [our translation keys](https://github.com/Adyen/adyen-ios/blob/master/Adyen/Assets/en-US.lproj/Localizable.strings) to your app's localizable.

SDK first checks for translation in your bundle, then fallback to our internal one.
The same way you can customize any translation line, or add a new language.

**Comment by tejasdthanki** [comment]
Hello @descorp / @mohammedDehairy ,

I wants to change language from my application.(e.g. I have screen from there user can choose language).so, I am asking you there is any param in adyen sdk that it can take user selected language.

**Comment by mohammedDehairy** [comment]
Hi @tejasdthanki ,

 What you're trying to do if I understood correctly is to override the system language chosen by the user in the iOS system settings.

 That is not supported out of the box from the checkout SDK, since the SDK localization follows the system language.

 But what you can do is take advantage of the `LocalizationParameters` object in the`DropInComponent.PaymentMethodsConfiguration()` that is passed to the `dropInComponent`:
1. First add a `.strings` file for every language you want your app to support, for example: `English.strings`, `Spanish.strings`, `Russain.strings`...etc, and in every file override the keys exposed by the checkout SDK.
2. Every time the user switches to a different language in your in-app settings, you create a LocalizationParameters with a custom table name, and pass the corresponding file name to the chosen language, for example you pass table name `Spanish` when user chooses Spanish.

```
let configuration = DropInComponent.PaymentMethodsConfiguration()
configuration.localizationParameters = LocalizationParameters(tableName: "Spanish")
        
let component = DropInComponent(paymentMethods: paymentMethods,
                                        paymentMethodsConfiguration: configuration,
                                        style: dropInComponentStyle,
                                        title: Configuration.appName)
component.delegate = self
present(component)
```
 
let me know if this works for you.

**Comment by tejasdthanki** [comment]
Hello @mohammedDehairy ,
I have added text from your localisation file to my localisation file right now just for only spanish("es").Please refer attached screenshot(localization.png).

![localization](https://user-images.githubusercontent.com/63439638/80482046-28615a80-8971-11ea-9296-73cbaf2562e4.png)
And write to below code
configuration.localizationParameters = LocalizationParameters(tableName: "Spanish")
and also try with
configuration.localizationParameters = LocalizationParameters(tableName: "es").

But not woking.(e.g. not translated text in SDK display text in english).Please refer attached screenshot.
![CreditCard](https://user-images.githubusercontent.com/63439638/80482287-94dc5980-8971-11ea-801b-76e789e93d6f.png)

**Comment by mohammedDehairy** [comment]
did you call your file `Spanish.strings`? because the table name passed to `LocalizationParameters` has to match the file name (without extension) that has the Spanish translations.

**Comment by tejasdthanki** [comment]
Hello @mohammedDehairy ,
My file name is Localizable.string (Spanish). Please refer attached screenshot.
![LocalizationSpanish](https://user-images.githubusercontent.com/63439638/80484269-0ec21200-8975-11ea-94bb-12b6747ee7ed.png)

**Comment by mohammedDehairy** [comment]
For the solution proposed to work, you need a different file for every supported language with a name other than `Localizable.strings`, since `Localizable.strings` is the default name the system uses when the user switches device language.

![Screen Shot 2020-04-28 at 2 00 19 PM](https://user-images.githubusercontent.com/2619933/80484822-a5cca100-8958-11ea-9625-3e8dd4bfdd2c.png)

and the `tableName` passed to the `LocalizationParameters` has to match the file name corresponding to the language chosen by the user.

**Comment by tejasdthanki** [comment]
Thanks @mohammedDehairy ,
Above solution is working for me.

**Comment by imadghanimi** [comment]
@mohammedDehairy @tejasdthanki 
please, can you tell me in which folder to create the MyLocalizable.strings files to use at LocalizationParameters(MyLocalizable: "Spanish")
