### ISSUE TITLE
3D Secure - TermUrl missing

### ISSUE THREAD

**Issue by designkros** [Adyen/adyen-ios#158]
Hi,

If I set `returnUrl: "app-url://success"`the 3D Secure works fine but if I set `returnUrl: "https://abc.xyz/success"`with a JS redirecting to `app-url://success` which was my desired behaviour, than the 3D Secure webpage says `1.0.23 Required element missing. TermUrl`.

I discussed this with support and we found out that this error was caused by the `returnUrl` and I managed to make it work but I guess there might be a problem in the Drop-In component.

It is able to handle GET redirect (from request with app-url://success) but is not able to handle POST redirect (from request with https://abc.xyz/success).

Now I found [this issue](https://github.com/Adyen/adyen-ios/issues/94) and I am I'm sad I didn't find this before spending several hours going through this problem. Not even after consulting with support that wasn't aware of this behaviour at first.

But - I believe that UIWebView and WKWebView both can load a request with POST http method.

**Comment by mohammedDehairy** [comment]
Hi @designkros ,

 We use SafariViewController, because its more friendly to users, since it integrates with normal Safari app experience like using the iOS keychain and autocomplete behavior, and also SafariViewController is more secure since it doesn't share much information with the host app.

 On the other hand host apps should be able to use https links as a returnUrl, that's a completely valid use case specially if you use universal links, so we need to investigate how this can be fixed.

Thanks for your question.

Mohamed

**Comment by mohammedDehairy** [comment]
Hi @designkros ,

 After some investigation, found out that in the `/payments` request, you can add two more parameters to the request to instruct the checkout api to give back a GET redirect instead of POST:
https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/v49/payments__reqParam_redirectToIssuerMethod
the two parameters are `redirectFromIssuerMethod` and `redirectToIssuerMethod`

Hope this helps

Mohamed

**Comment by olivermrbl** [comment]
Hey @mohammedDehairy!

Thanks for shedding light on this issue. Your proposal solved it for me!

I am curious though... Would this fix mean, that we don't have to handle POST redirect at all? Since all are using GET. 

Looking forward to hearing from you.

Thanks!

**Comment by mohammedDehairy** [comment]
Hi @olivermrbl ,

 if `redirectToIssuerMethod` is set to `GET`, then yes, you don't need to handle `POST` redirects.

Mohamed

**Comment by olivermrbl** [comment]
Thank you for the rapid response Mohamed! Appreciate it :)
