### ISSUE TITLE
[NEED ASSIST] Generate Token using Own UI to make payment later.

### ISSUE THREAD

**Issue by bhargavbajani-simformsolutions** [Adyen/adyen-ios#1665]
Describe the challenge
I want to integrate Adyen as our payment processor into our existing application, where we've already implemented a custom UI for capturing card details. The goal is to generate a token representing the user's card details, store this token securely on our server, and enable functionalities like adding, updating, and deleting card details for users.

**Describe the challenge**
How can achieve this functionality using SDK. 

Note: Using carthage in project and Project in Objective C which is not concern for now.

**Comment by descorp** [comment]
Hey @bhargavbajani-simformsolutions 

Most of this functionality lay outside iOS SDK scope.
Check our [Tokenization](https://docs.adyen.com/online-payments/tokenization/) and  [Manage tokens](https://docs.adyen.com/online-payments/tokenization/managing-tokens/) documentation.

If you have any issues with iOS code or this SDK - please create dedicated issue on GitHub.
If you have any issues or questions on Tokenisation or [backend API](https://docs.adyen.com/api-explorer/Checkout/71/post/payments) - please reach out [Adyen Support](https://www.adyen.help/hc/en-us/requests/new?ticket_form_id=360000705420)

**Comment by bhargavbajani-simformsolutions** [comment]
@descorp  is there any way to do it with a provided drop-in UI or customisable Provided UI by SDK? The requirement is Store card for future payment which is happening from our other app. 

Can I get an exact document for this?

**Comment by descorp** [comment]
Hey @bhargavbajani-simformsolutions 

> we've already implemented a custom UI for capturing card details.

Since you have mentioned custom UI , I assumed you are not looking to use any of Adyen UI.

---

See [Create-a-token](https://docs.adyen.com/online-payments/tokenization/advanced-flow/#create-a-token) documentation:

You can [create new stored card](https://docs.adyen.com/payment-methods/cards/ios-component/?tab=stored-4_2#stored-card-payments) using our `CardComponent` and **0 amount**. Make sure to specify correct [recurringProcessingModel](https://docs.adyen.com/api-explorer/Checkout/latest/post/payments#request-recurringProcessingModel) and [storePaymentMethod](https://docs.adyen.com/api-explorer/Checkout/latest/post/payments#request-storePaymentMethod) set to `true`.

The rest of "token management" is not part of iOS SDK and should be performed thought API calls (link in my previous message). 

---

You can use our award-winning [Postman Adyen API](https://www.postman.com/adyendev/workspace/adyen-apis/collection/25716737-46ad970e-dc9e-4246-bac2-769c6083e7b5).
