### ISSUE TITLE
Add/remove cards with SDK without payment

### ISSUE THREAD

**Issue by ihor-vovk-lohika** [Adyen/adyen-ios#29]
Hello. Is it possible to add/remove credit/debit cards for future usage with your SDK and without actual payment? We would like the user to be able to manage their cards in settings.

Maybe, by generating a fake payment request with 0 amount or something like that?

**Comment by joostvandijk** [comment]
Hi @ihor-vovk-lohika,

It's possible, but the SDK's UI isn't specifically made for it. However, you could do a 0 amount payment and set `enableRecurring` to `true` in your `/setup` request. You can then use our `AppearanceConfiguration` class to change the `checkoutButtonTitle` to something other than "Pay".

Kind regards,

Joost

**Comment by joostvandijk** [comment]
Our UI also supports removing stored cards. If you'd like to build a custom UI, you'd need the `deletePreferred(paymentMethod:completion:)` method in `PaymentRequest`.

**Comment by Lukaz32** [comment]
> Our UI also supports removing stored cards. If you'd like to build a custom UI, you'd need the `deletePreferred(paymentMethod:completion:)` method in `PaymentRequest`.

Hello @joostvandijk ,
how could I allow the user to remove his stored cards from the Component UI ?

**Comment by descorp** [comment]
Hi @Lukaz32 

Unfortunately, this feature is not available on v3.

If you believe this is nice to have  - please, create a new feature request and describe your use-case. 
We will prioritize it and add it to future releases.

To my knowledge, the API didn't change since v2, so if you need it ASAP - feel free to fork our DropIn Component and modify it based on 'deletePreferred(paymentMethod:completion:)'. 
We appreciate any contributions, so PRs are welcomed. 😉

**Comment by Lukaz32** [comment]
HI @descorp 
Thanks for the quick reply.
I'll consider doing just that.

Cheers
