### ISSUE TITLE
[Feature] Swish payment method

### ISSUE THREAD

**Issue by jesperjohansson** [Adyen/adyen-ios#343]
**Is your feature request related to a problem? Please describe.**
Hello! Swish is a very popular payment method in Sweden and our customers frequently request us (Ancon) to add support for Swish in our app. We are moving away from a web-based solution to instead use the native drop-ins which don't seem to support Swish.

**Describe the solution you'd like**
Add a Swish component that can also be used with the dropin component.

**Describe alternatives you've considered**
I have tested adding Swish locally and I seem to have got it working in the TEST environment. I thought I should request this feature before going further (I'm novice in Swift 😛).

**Additional context**
The web dropin has support for Swish.

**Comment by descorp** [comment]
Hi @jesperjohansson 

Thank you for the feedback! 
I believe the confusion is caused by the fact that mobile is not mentioned [in our Swish docs](https://docs.adyen.com/payment-methods/swish).

Swish is a simple redirect payment method and it is supported on mobile DropIn as well.

To enable it - please select country and currency to `SE`, `SEK` as mentioned in [web docs](https://docs.adyen.com/payment-methods/swish/web-drop-in#show-swish-in-your-payment-form)

<img width="526" alt="Screenshot 2021-01-15 at 12 55 25" src="https://user-images.githubusercontent.com/2648655/104724639-41917d80-5731-11eb-826e-59605758b0db.png">

**Comment by jesperjohansson** [comment]
@descorp Oh thats great! Sorry for the inconvenience, but when I use the Swish payment method and I am redirected back to the Adyen app I get an encoder error on [RedirectDetails.swift:L36](https://github.com/Adyen/adyen-ios/blob/df6f7cd2ed097c923b117aca7ebec59be1876d4d/AdyenActions/Components/Redirect/RedirectDetails.swift#L36). It seems I get only one query param called "pp" when i print `queryParameters` in [extractKeyValuesFromURL()](https://github.com/Adyen/adyen-ios/blob/df6f7cd2ed097c923b117aca7ebec59be1876d4d/AdyenActions/Components/Redirect/RedirectDetails.swift#L55):
```
=== queryParameters ===
["pp": "IntCgsB/jYwpkzhO5bjJGcjIyU9L4G3Mc4Q/uKlWLoLQ5tWMLZSb7geXNoNKuu+mSBBz1vgA74aNq7uEiy6LRI5tfLyP5c4tfAp94KjOeLhZ9CCI62CSWt0ThjCq+7woOF8uUpS/m67rDp/K+AiJcQ=="]
```

**Comment by descorp** [comment]
Hey @jesperjohansson 

This could be a result of a configuration in your merchant account:
`checkoutGluePagesEnabledTxVariants` needs to be enabled with the variant `swish`

**Comment by jesperjohansson** [comment]
@descorp Ah ok! Thanks, I'll contact the support about enabling `checkoutGluePagesEnabledTxVariants`
