### ISSUE TITLE
Redirection from VippsMT app is not detecting

### ISSUE THREAD

**Issue by Cemoo** [Adyen/adyen-ios#346]
Hi, I have an issue about redirection from VippsMT app to my app. When I choose Vipps from payment methods,  It opens Safari page and showed popup asks like "Open Vipps app". I am tapping ok button and navigates me VippsMT app. When I finished payment on VippsMT I cannot detect redirection to my app, because of Safari remains open forward of my app.

How can I solve this problem? Can you help me please?

**Comment by descorp** [comment]
Hey @Cemoo 

Thanks for feedback!

It opens in-app safari or Safari app?
Does `returnUrl` works for other payment methods?

**Comment by Cemoo** [comment]
Hi @descorp , I think it is in app Safari. You can check it out from ss. We ll use only Vipps for now, working on that.

Thanks

![IMG_F904375DD50A-1](https://user-images.githubusercontent.com/5932810/105227507-79098b00-5b72-11eb-881d-ab993b6f8fff.jpeg)

**Comment by descorp** [comment]
Indeed this is in-app browser.
It makes a web redirect (that is why you see in-app browser) to a custom url `vippsmt://####`.
After Vipps is done it make same move - opens in-app browser to redirect to your app.

Make sure that your url-scheme and `returnUrl` is [setup correctly](https://docs.adyen.com/payment-methods/vipps/ios-component#make-payment)

**Comment by Cemoo** [comment]
Hi @descorp 

This code working when going to vippsMT app. My problem is about coming back from vippsMT app.

**Comment by descorp** [comment]
Hey @Cemoo 

About:
`application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey: Any] = [:]) -> Bool` 
This method is called when customURLScheme of your app is called. 
If a URL arrives while your app is suspended or running in the background, the system moves your app to the foreground prior to calling this method.

What do you see when you completed payment in Vipps?
Could you provide a video/gif ?

**Comment by Cemoo** [comment]
Hi @descorp  

When payment is completed I see the Safari page opened state. You can see it like I attached above. Safari page is not closing  itself.

**Comment by Cemoo** [comment]
By the way, do you support universal linking? @descorp

**Comment by descorp** [comment]
Hey @Cemoo 

Yes, universal links are also supported.
We recommend using custom schemes - universal links could be confusing for the shopper and may lead to a state when link is always opened in the browser app.

> When payment is completed I see the Safari page opened state. You can see it like I attached above. Safari page is not closing itself.

Is it blank? Do you see a prompt to open "Your App" ?
Could you share the URL?

For the reference I am attaching video from our demo app.

https://user-images.githubusercontent.com/2648655/105685370-47881b00-5ef6-11eb-994f-fb25f0017913.mov

**Comment by Cemoo** [comment]
How can safari ask "Open AdyenUIHost" here? Did you add only Vipps custom url scheme? Do we need to add two url scheme?

**Comment by Cemoo** [comment]
I closed issue accidentally sorry.

**Comment by descorp** [comment]
Hey @Cemoo 

> How can safari ask "Open AdyenUIHost" here?

Our backend uses same redirect technic to open Vipps and to get back to your app:

1. Make [payment request](https://docs.adyen.com/payment-methods/vipps/ios-drop-in#payments) with `"returnURL": "my-app://"`.
2. Our backend returns [Redirect Action](https://docs.adyen.com/payment-methods/afterpaytouch/ios-drop-in#-payments-response) with URL. 
E.x. `https://checkoutshopper-test.adyen.com/checkoutshopper/checkoutPaymentRedirect?redirectData=####`
3. When URL processed by Safari, it performs redirect to `vippsmt://?token=####`; the payload contains payment parameters and **return link** to a `checkoutPaymentRedirect`, similar to the one you received in Redirect Action.
4. iOS opens Vipps with payment parameters. 
5. When Vipps is finished, it calls **return link** and it performs redirect in exactly same manner as step 3 to `my-app://?redirectResult=####`. 
6. iOS opens your app with payment parameters via `AppDelegate.application(app:open url:options:) -> Bool`

> Did you add only Vipps custom url scheme? Do we need to add two url scheme? 

You don't need to know Vipps custom URL scheme, since redirect is taken care of by our backend.
You only need to provide your app's custom URL scheme in `payment` request, so our backend knows where to redirect after payment is done.

**Comment by descorp** [comment]
Hey @Cemoo 

was my last comment any how helpful?

**Comment by Cemoo** [comment]
Yeah helpful @descorp  thanks. I ll open this because I got another one :)
