### ISSUE TITLE
[Feature] Attempt opening BankID app on 3DS

### ISSUE THREAD

**Issue by jesperjohansson** [Adyen/adyen-ios#452]
**Is your feature request related to a problem? Please describe.**
Hello! When making payments in online stores in Sweden, its extremely common that you use the app BankID to verify/authorise your purchase. Therefore almost all websites and apps attempts to open BankID automatically/show the native dialog that asks if you want to open the BankID app. Currently we only get the result in the attached screenshot which makes for bad user experience because you have to manually navigate to and open the BankID app.

![image](https://user-images.githubusercontent.com/21033162/114146141-88010d80-9917-11eb-9614-45deff617bbc.png)

**Describe the solution you'd like**
Make it so that the 3DS step for BankID attempts to open the BankID app.

**Describe alternatives you've considered**
Is there a way we can implement this ourselves on our side?

**Additional context**
v3.8.3, Drop-in

**Comment by ACathelin** [comment]
Hi Jesper, 

This is unfortunately a known limitation of the 2.1.0 SDKs. 
Those SDKs are defined and designed by [EMVCo](https://www.emvco.com/emv-technologies/3d-secure/).
Each SDKs available have to comply with the EMVCo's design. 
Therefore Adyen cannot perform the desired change, since it is not part of the 2.1.0 or 2.2.0 specs.

The 2.2.0 SDKs will improve the overall user experience for the `returning of the consumer to the merchant app`, but the overall user experience (including your recommendation) should be fixed in the 2.3.0 version of the EMV 3DS Protocol.

Please note that 2.3.0 is currently still in a _draft_ process on the EMVCo side and therefore will not be adopted in the near future (given the fact that EMVCo needs to design the tests cases for the certification, scheme certifications, and implementation of 2.3.0 by each ACSes).

**Comment by jesperjohansson** [comment]
Ah okay, thank you for the info!
