### ISSUE TITLE
Drop-in accepting expired months in current year

### ISSUE THREAD

**Issue by tidalboot** [Adyen/adyen-ios#461]
The drop in is currently not showing expired months in the current year as expired/invalid. For example at the time of raising this bug in April the drop in "ticks" February 2021 (02/21) I the expiry date where it shouldn't.

I've attached a screenshot as an example and have left the details sparse on purpose as the issue is pretty easy to replicate and isn't a detailed or complex issue but happy to provide any extra info as needed. 

Tested on latest non-beta version (3.8.4)

![IMG_2146](https://user-images.githubusercontent.com/4403178/115252130-1a2cc100-a123-11eb-94b7-9abd2d661843.jpg)

**Comment by descorp** [comment]
Hey @tidalboot 

This is intentional - in some rare circumstances expired card could still be used.
For example, during COVID last year, governments of some countries prolonged usage of expired cards to keep people from going to local bank offices.

The issuing bank has a final word here, and since Adyen can't guarantee that the card is no longer work with 100% - we are allowing a ±3 month difference.

**Comment by tidalboot** [comment]
Aha gotcha! Makes perfect sense to me. 

Always cool seeing these weird banking quirks. 

Thanks for getting back so quickly, will close this issue down 👍
