### ISSUE TITLE
[NEED ASSIST] Carthage integration project configuaration

### ISSUE THREAD

**Issue by jonathanlu813** [Adyen/adyen-ios#514]
**Describe the challenge**
We are integrating `adyen-ios` to our project with Carthage. After running `carthage update`, we followed the carthage guide and added `Adyen.framework`, `AdyenCard.framework` and `Adyen3DS2.framework` to the embedded frameworks list and the carthage copy list. However, this will cause the app to crash while launching because of dynamic framework linking issue with `Adyen3DS2.framework`"

```
Underlying Error: Crash: Retailer (17947) <external symbol>: Namespace CODESIGNING, Code 0x2. dyld: launch, loading dependent libraries
DYLD_SHARED_CACHE_DIR=/Users/travis/Library/Developer/CoreSimulator/Caches/dyld/20E232/com.apple.CoreSimulator.SimRuntime.iOS-14-2.18B79
DYLD_ROOT_PATH=/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 14.2.simruntime/Contents/Resources/RuntimeRoot
DYLD_LIBRARY_PATH=/Users/travis/Library/Developer/Xcode/DerivedData/Retailer-douctiwtlvmobqghnihpvgofmjlj/Build/Products/Debug Staging-iphonesimulator:/Users/travis/Library/Developer/Xcode/DerivedData/Retailer-douctiwtlvmobqghnihpvgofmjlj/Build/Products/Release-iphonesimulator
DYLD_PRINT_STATISTICS=YES
DYLD_INSERT_LIBRARIES=/Users/travis/Library/Developer/Xcode/DerivedData/Retailer-douctiwtlvmobqghnihpvgofmjlj/Build/Products/Debug Staging-iphonesimulator/Retailer.app/Frameworks/libXCTestBundleInject.dylib:/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 14.2.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libMainThreadChecker.dylib
DYLD_FALLBACK_FRAMEWORK_PATH=/Library/Developer/CoreSimulator/Profiles/Runtimes
@rpath/Adyen3DS2.framework/Adyen3DS2.
```
We experimented a bit and found that if we remove the 3DS2 framework from the embedded framework list, but keep it in the copy list could fix the issue. Can you please verify it is the correct configuration?

**Documentation update (optional)**
If applicable, attach a link to documentation page that wasn't helpful / missing information.
What would you like to see there?
https://github.com/Adyen/adyen-ios#carthage

**Screenshots**
Embedded Frameworks:
![](https://user-images.githubusercontent.com/1576268/119243948-75463f00-bb39-11eb-9df9-c9da1a47b5b3.png)
Carthage Copy Famework:
![](https://user-images.githubusercontent.com/1576268/119243952-842cf180-bb39-11eb-9b63-aa86126df017.png)
![](https://user-images.githubusercontent.com/1576268/119243956-9870ee80-bb39-11eb-9c6e-282f75663555.png)

**Comment by descorp** [comment]
Hey @jonathanlu813 

Thanks for reaching out!

Quick question:
What version of SDK and Xcode are you using?

**Comment by jonathanlu813** [comment]
Hey @descorp, I'm on Xcode 12.5 and tried on iOS 14.5 and 13.5.

**Comment by descorp** [comment]
hm.. 
I am surprised that you were able to run `carthage update` on Xcode 12+.

Regarding your configuration:
I would not recommend to keep frameworks unsigned - we can't guarantee that without signing it will be excepted by AppStore. 

FYI
I would encourage you to use SPM :D

From our perspective Carthage become a least stable package management tool since Xcode 12 release.
With introduction of arm64 we were forced to use **fat libraries**. 
To make it work you can use [carthage.sh](https://github.com/Adyen/adyen-ios/blob/develop/Scripts/carthage.sh) - it will manage all slices for device and simulator:

`carthage.sh update --use-xcframeworks`  

Than link all **AdyenXXX.xcframework** from *Carthage/Build/* and  **Adyen3DS2.xcframework**  from *Carthage/Checkouts/adyen-3ds2-ios/XCFramework/Dynamic/*.

We will update our documentation and integrations "how to" for v4 release, many thanks!

**Comment by jonathanlu813** [comment]
Thanks for responding! I forgot to mention we used the `EXCLUDED_ARCHS` workaround(as suggested by the several issues on Carthage repo) for our Carthage scripts. 

We are currently using SPM to resolve Adyen and Carthage for other dependencies, but we would love to use one manager to manage all the dependencies in the future. Please let us know when the v4 release is out. We will see how we can have a better integration.
