### ISSUE TITLE
 adyen-ios support objective c

### ISSUE THREAD

**Issue by ronakcc** [Adyen/adyen-ios#805]
adyen-ios support objective c??
How to add  adyen-ios SDK in my objective c application.
Thank you!

**Comment by descorp** [comment]
Hey @ronakcc 

Thanks for reaching out!

Unfortunately, the SDK is not immediately usable for ObjC projects: you would have to create a proxy/facade swift class(s) that inherits from NSObject and incorporate the SDK's components. 
Your objC code should call this proxy/facade objects instead of the SDK directly.
