### ISSUE TITLE
Example provideAdditionalDetails

### ISSUE THREAD

**Issue by kadikraman** [Adyen/adyen-ios#90]
We are looking to implement 3D secure payments on `v2.8.4`.

We can not migrate to `v3` at this point, since `v3` removes `PaymentController` and `CheckoutController` which is what we are currently using to communicate with the system, so it would have to be a complete rewrite.

[This issue](https://github.com/Adyen/adyen-ios/issues/73) references an implementation example for `provideAdditionalDetails`, but I am unable to find it on the [docs site](https://docs.adyen.com/checkout/ios-sdk/). Indeed, I can find no reference to `provideAdditionalDetails` at all, and no documentation for past versions of the sdk.

Is there a configuration example for `provideAdditionalDetails` you could direct us to?

Thank you!

**Comment by joostvandijk** [comment]
Hi @kadikraman,

The implementation example can be found [here](https://code.is.adyen.com/iOS/adyen-checkout-ios/src/tag/2.8.4/Examples/Custom%20Integration%20Example/Custom%20Integration%20Example/PaymentRequestManager.swift#L249). Since the very limited amount of users that integrated with the custom integration, there is no documentation for this flow on the documentation website (yet). The example integration should help getting you started, but feel free to ask me any question if something remains unclear.

Best,

Joost

**Comment by kadikraman** [comment]
Thanks @joostvandijk - I'll check it out!
