### ISSUE TITLE
[NEED ASSIST] Certificates expiration in Adyen3DS2 embedded SDK

### ISSUE THREAD

**Issue by eduardourso** [Adyen/adyen-ios#924]
When doing a 3DS challenge on an iOS app that uses the AdyenSDK version `4.7.3` we are receiving the following warning:

> One or more of the certificates embedded in Adyen3DS2 will expire on June 24th, 2022. To make sure you have the latest certificates, always upgrade to the latest SDK version. We'll make sure the certificates are updated well before the mentioned date.

Is there a plan to update the certificates that are throwing the warning? If the SDK is not updated until June 24th, 2022 would it impact our application in any way?

**Comment by mohammedDehairy** [comment]
Hi @eduardourso ,

The certificate is updated, but we kept the warning because the old certificate is still there for backward compatibility, so the warning is a bit misleading, you can ignore the warning, and sorry for the inconvenience, we'll remove it with the next release of the 3DS2 SDK.

kind regards

**Comment by eduardourso** [comment]
Perfect, thank you for the heads up. We are looking forward to the next release. Cheers 👍
