### ISSUE TITLE
Stored Payment Methods with DropIn Component

### ISSUE THREAD

**Issue by cristian-cojocaru** [Adyen/adyen-ios#97]
Hello,

I have some 'issues' implementing stored payments methods on iOS. I use drop-in component and last version of sdk 3.1.1.

In app I receive stored card details from backend (https://pastebin.com/raw/vF6vJnGa payment/methods endpoint), json formatted as in docs,  
pass them to DropInComponent (create a "PaymentMethods" object and "showsStorePaymentMethodField" set on true), but it does't present a screen with stored cards.

I tried to make a workaround, create a CardComponent object with first object from "storedPaymentMethods"  and to make a custom Ui, but in didSubmit function,   encryptedCardNumber, encryptedExpiryMonth, encryptedExpiryYear are nil and next request, payment/create, fails.

There is a build-in UI in Adyen to present stored cards using last version of sdk and drop in?

Code I worte as in docs:

            let data = try JSONSerialization.data(withJSONObject: paymentMethodsResponse, options: .prettyPrinted)  
            let paymentMethods: PaymentMethods = try JSONDecoder().decode(PaymentMethods.self, from: data)
            
            let configuration = DropInComponent.PaymentMethodsConfiguration()
            configuration.card.publicKey = self.publicKey
            configuration.card.showsHolderNameField = true
            configuration.card.showsStorePaymentMethodField = true
            
            self.dropInComponent = DropInComponent(paymentMethods: paymentMethods, paymentMethodsConfiguration: configuration)
            self.dropInComponent?.delegate = self
            self.dropInComponent?.environment = .test

            if let delegate = self.delegate, let dropin = self.dropInComponent {
                delegate.present(dropin.viewController, animated: true, completion: nil)
            }

**Comment by joostvandijk** [comment]
Hey @cristian-cojocaru,

My apologies for the late reply. The issue is that the payment methods are stored as `ContAuth` and not `Ecommerce`. `ContAuth` is used for payments without shopper interaction (like a subscription charge), which is why they aren't shown in the Drop-In. If you store the payment method by simply setting `storePaymentMethod` = `true` in the root of your payments request when you want to store the payment method, it should store it as `Ecommerce` and become visible in the Drop-In.

Best,

Joost

**Comment by ChrisHG-Ticketer** [comment]
Hi Joost!

I'm having the same issue as Cristian above. It seems there is a mismatch between the docs here (https://docs.adyen.com/checkout/tokenization#recurring-transactions-based-on-business-models), the API Explorer (which only shows using the StorePaymentDetails flag) and the iOS storedPaymentMethods filtering.

The matrix in the documentation says that we should set 
```
ShopperInteraction : "Ecommerce",
RecurringProcessingModel:"CardOnFile" 
```
with the initial transaction to store the card details. This works as expected. When we subsequently call paymentMethods, we get back the storedCardDetails, but with only "ContAuth" showing in the supportedShopperInteractions. Testing directly from the server-side using the C# SDK, these details work fine when submitted for payment, because as the matrix suggests, "ContAuth" is used for an "Online purchase where shopper uses previously stored card payment details."

The problem seems to be (at least from our iOS developer's perspective) is that the stored payment methods are filtered to only show methods supporting "Ecommerce". However, this doesn't make sense according to the docs! Should the filter actually be on the other payment methods (which do require "Ecommerce"), rather than the stored ones - which by the matrix definition require "ContAuth"?

Here is the problematic section: 
```
internal lazy var components: SectionedComponents = {
        // Filter out payment methods without the Ecommerce shopper interaction.
        let storedPaymentMethods = paymentMethods.stored.filter { $0.supportedShopperInteractions.contains(.shopperPresent) }
        
        return SectionedComponents(
            stored: storedPaymentMethods.compactMap { component(for: $0) },
            regular: paymentMethods.regular.compactMap { component(for: $0) }
        )
    }()
```

Would it make more sense to be:

```
internal lazy var components: SectionedComponents = {
        // Filter out payment methods without the Ecommerce shopper interaction.
        let regularPaymentMethods = paymentMethods.regular.filter { $0.supportedShopperInteractions.contains(.shopperPresent) }
        
        return SectionedComponents(
            stored: paymentMethods.stored.compactMap { component(for: $0) },
            regular: regularPaymentMethods.compactMap { component(for: $0) }
        )
    }()
```

I also had a quick look at the Android implementation and couldn't see this filtering happening there... is it correct? 

I tried adding the storePaymentMethod = true to our request as you suggested to Cristian above, however this broke the test, it just returned a 500 error. 

Thanks in advance!

**Comment by joostvandijk** [comment]
Hi @ChrisHG-Ticketer,

I get why this is confusing. `ContAuth` is actually used for payments with previously stored details where the shopper is **not** present. For example, this method is used for recurring subscription charges. In case the shopper is present during the payment, a CVC needs to be entered, and thus the shopper interaction type is `Ecommerce`. Because in the drop-in solution, the shopper is always present, only `Ecommerce` payment methods are shown.

Instead of the two fields you're sending in the initial request, try replacing them with `storePaymentMethod` = `true`. This should store the payment method as both `ContAuth` and `Ecommerce`. If you're getting a 500 error, can you please email me at joost.vandijk@adyen.com with the PSP reference of the response? If it's not in the body, it can be found in the response headers.

Thanks!

**Comment by bukira** [comment]
Can Adyen do stored payment methods via the CardComponent or ONLY vie the DropInComponent?

**Comment by joostvandijk** [comment]
@bukira Both components only provide UI and no payments logic. All the logic is handled by your requests to our backend API.

**Comment by bukira** [comment]
I am using your PaymentMethods.json which has saved cards, if use the DropInComponent then I can see the saved cards, but if I use the CardComponent on its own I don't, I just get prompted to use a new card

**Comment by joostvandijk** [comment]
@bukira It's indeed the DropInComponent that lets you select stored cards. If you pass a single stored card to the CardComponent, the UI will change and only ask for the CVC/CVV code, and not the full card details.

**Comment by bukira** [comment]
ah right got ya, to use this I need to parse the paymentMethods and present the stored cards myself to the user and let them select one :-)

**Comment by joostvandijk** [comment]
Exactly :)
